//! Memory and aggregate access operations.

/// `cir.alloca`
/// Defines a scope-local variable
///
/// The `cir.alloca` operation defines a scope-local variable.
///
/// The presence of the `const` attribute indicates that the local variable is
/// declared with C/C++ `const` keyword.
///
/// The `dynAllocSize` specifies the size to dynamically allocate on the stack
/// and ignores the allocation size based on the original type. This is useful
/// when handling VLAs or the `alloca` builtin and is omitted when declaring
/// regular local variables.
///
/// The `cleanup_dest_slot` attribute indicates that this was a temporary
/// alloca generated by the compiler to handle cleanup exit dispatching.
///
/// The result type is a pointer to the input's type.
///
/// Example:
///
/// ```
/// // int count;
/// %0 = cir.alloca "count" align(4) : !cir.ptr<i32>
///
/// // int *ptr;
/// %1 = cir.alloca "ptr" align(8) : !cir.ptr<!cir.ptr<i32>>
/// ...
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Alloca {
    pub addr: super::ValueId,
    pub addr_ty: crate::types::Type,
    /// 64-bit unsigned integer
    pub dyn_alloc_size: Option<super::ValueId>,
    /// string attribute
    pub name: String,
    /// unit attribute
    pub init: bool,
    /// unit attribute
    pub constant: bool,
    /// unit attribute
    pub cleanup_dest_slot: bool,
    /// 64-bit signless integer attribute whose minimum value is 1
    pub alignment: u64,
    /// array of cir.annotation attributes
    pub annotations: Option<crate::attrs::Attribute>,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.base_class_addr`
/// Get the base class address for a class/struct
///
/// The `cir.base_class_addr` operaration gets the address of a particular
/// non-virtual base class given a derived class pointer. The offset in bytes
/// of the base class must be passed in, since it is easier for the front end
/// to calculate that than the MLIR passes. The operation contains a flag for
/// whether or not the operand may be nullptr. That depends on the context and
/// cannot be known by the operation, and that information affects how the
/// operation is lowered.
///
/// The validity of the relationship of derived and base cannot yet be verified.
/// If the target class is not a valid base class for the object, the behavior
/// is undefined.
///
/// Example:
/// ```c++
/// struct Base { };
/// struct Derived : Base { };
/// Derived d;
/// Base& b = d;
/// ```
/// will generate
/// ```
/// %3 = cir.base_class_addr %1 : !cir.ptr<!rec_Derived> nonnull [0] -> !cir.ptr<!rec_Base>
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BaseClassAddr {
    pub base_addr: super::ValueId,
    pub base_addr_ty: crate::types::Type,
    /// CIR pointer type
    pub derived_addr: super::ValueId,
    /// index attribute
    pub offset: crate::attrs::Attribute,
    /// unit attribute
    pub assume_not_null: bool,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.base_data_member`
/// Cast a derived class data member pointer to a base class data member pointer
///
/// The `cir.base_data_member` operation casts a data member pointer of type
/// `T Derived::*` to a data member pointer of type `T Base::*`, where `Base`
/// is an accessible non-ambiguous non-virtual base class of `Derived`.
///
/// The `offset` parameter gives the offset in bytes of the `Base` base class
/// subobject within a `Derived` object.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BaseDataMember {
    pub result: super::ValueId,
    pub result_ty: crate::types::Type,
    /// CIR type that represents a pointer-to-data-member in C++
    pub src: super::ValueId,
    /// index attribute
    pub offset: crate::attrs::Attribute,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.base_method`
///
/// Cast a derived class pointer-to-member-function to a base class
/// pointer-to-member-function
///
///
/// The `cir.base_method` operation casts a pointer-to-member-function of type
/// `Ret (Derived::*)(Args)` to a pointer-to-member-function of type
/// `Ret (Base::*)(Args)`, where `Base` is a non-virtual base class of
/// `Derived`.
///
/// The `offset` parameter gives the offset in bytes of the `Base` base class
/// subobject within a `Derived` object.
///
/// Example:
///
/// ```
/// %1 = cir.base_method %0 [16] : !cir.method<!cir.func<(!s32i)> in !rec_Derived> -> !cir.method<!cir.func<(!s32i)> in !rec_Base>
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct BaseMethod {
    pub result: super::ValueId,
    pub result_ty: crate::types::Type,
    /// CIR type that represents C++ pointer-to-member-function type
    pub src: super::ValueId,
    /// index attribute
    pub offset: crate::attrs::Attribute,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.clear_cache`
/// Clear the processor's instruction cache if required.
///
/// The `cir.clear_cache` operation provides a representation for the
/// `__builtin__clear_cache` builtin and corresponds to the
/// `llvm.clear_cache` intrinsic in LLVM IR.
///
/// This operation ensures visibility of modifications in the specified
/// range to the execution unit of the processor. On targets with
/// non-unified instruction and data cache, the implementation flushes
/// the instruction cache.
///
/// On platforms with coherent instruction and data caches (e.g., x86),
/// this intrinsic is a nop. On platforms with non-coherent instruction
/// and data cache (e.g., ARM, MIPS), the operation will be lowered
/// either to appropriate instructions or a system call, if cache
/// flushing requires special privileges.
///
/// The default behavior is to emit a call to `__clear_cache` from the
/// runtime library.
///
/// This operation does not empty the instruction pipeline. Modifications
/// of the current function are outside the scope of the operation.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClearCache {
    /// pointer to void type
    pub begin: super::ValueId,
    /// pointer to void type
    pub end: super::ValueId,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.clear_padding`
/// Clear Padding Operation
///
/// This operation represents a `__builtin_clear_padding` call, which sets all
/// padding bits in the pointee `arg` to zero. The `arg`'s alignment is also
/// stored in this operation so we can properly emit the stores/loads later.
///
/// Offsets into the variable are stored as an `OffsetPairAttr`.
///
/// During LLVM-IR lowering, this is converted into `getelementptr` and `store`
/// operations.
///
/// Example:
///
/// ```
/// cir.clear_padding(align(1) %1,
///                   [#cir.offset_pair<0, 2>, #cir.offset_pair<6, 8>])
///                   : <rec_Type> -> ()
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ClearPadding {
    pub arg: super::ValueId,
    /// 64-bit signless integer attribute whose minimum value is 1
    pub alignment: u64,
    /// array of padding locations
    pub padding: crate::attrs::Attribute,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.copy`
/// Copies contents from a CIR pointer to another
///
/// Given two CIR pointers, `src` and `dst`, `cir.copy` will copy the memory
/// pointed by `src` to the memory pointed by `dst`.
///
/// The number of bytes copied is inferred from the pointee type. The pointee
/// type of `src` and `dst` must match and both must implement the
/// `DataLayoutTypeInterface`. The pointers may differ in address space (e.g.
/// when assigning through an address-space-qualified pointer); when the two
/// pointer types differ, both are printed, `src` first.
///
/// The `volatile` keyword indicates that the operation is volatile.
///
/// The `skip_tail_padding` keyword indicates that only the data bytes should
/// be copied, excluding any tail padding. This is used when copying
/// potentially-overlapping subobjects where the tail padding might be occupied
/// by other objects (e.g. fields marked with `[[no_unique_address]]`). This
/// is only valid when the pointee type is a record type.
///
/// Examples:
///
/// ```
///   // Copying contents from one record to another:
///   cir.copy %0 to %1 : !cir.ptr<!record_ty>
///
///   // Copying without tail padding (for overlapping subobjects):
///   cir.copy %0 to %1 skip_tail_padding : !cir.ptr<!record_ty>
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Copy {
    pub dst: super::ValueId,
    pub src: super::ValueId,
    /// 64-bit signless integer attribute
    pub dst_alignment: Option<crate::attrs::Attribute>,
    /// 64-bit signless integer attribute
    pub src_alignment: Option<crate::attrs::Attribute>,
    /// unit attribute
    pub is_volatile: bool,
    /// unit attribute
    pub skip_tail_padding: bool,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.derived_class_addr`
/// Get the derived class address for a class/struct
///
/// The `cir.derived_class_addr` operaration gets the address of a particular
/// derived class given a non-virtual base class pointer. The offset in bytes
/// of the base class must be passed in, similar to `cir.base_class_addr`, but
/// going into the other direction. This means lowering to a negative offset.
///
/// The operation contains a flag for whether or not the operand may be nullptr.
/// That depends on the context and cannot be known by the operation, and that
/// information affects how the operation is lowered.
///
/// The validity of the relationship of derived and base cannot yet be verified.
/// If the target class is not a valid derived class for the object, the
/// behavior is undefined.
///
/// Example:
/// ```c++
/// class A {};
/// class B : public A {};
///
/// B *getAsB(A *a) {
///   return static_cast<B*>(a);
/// }
/// ```
///
/// leads to
/// ```
///   %2 = cir.load %0 : !cir.ptr<!cir.ptr<!rec_A>>, !cir.ptr<!rec_A>
///   %3 = cir.base_class_addr %2 : !cir.ptr<!rec_B> [0] -> !cir.ptr<!rec_A>
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DerivedClassAddr {
    pub derived_addr: super::ValueId,
    pub derived_addr_ty: crate::types::Type,
    /// CIR pointer type
    pub base_addr: super::ValueId,
    /// index attribute
    pub offset: crate::attrs::Attribute,
    /// unit attribute
    pub assume_not_null: bool,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.derived_data_member`
/// Cast a base class data member pointer to a derived class data member pointer
///
/// The `cir.derived_data_member` operation casts a data member pointer of type
/// `T Base::*` to a data member pointer of type `T Derived::*`, where `Base`
/// is an accessible non-ambiguous non-virtual base class of `Derived`.
///
/// The `offset` parameter gives the offset in bytes of the `Base` base class
/// subobject within a `Derived` object.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DerivedDataMember {
    pub result: super::ValueId,
    pub result_ty: crate::types::Type,
    /// CIR type that represents a pointer-to-data-member in C++
    pub src: super::ValueId,
    /// index attribute
    pub offset: crate::attrs::Attribute,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.derived_method`
///
/// Cast a base class pointer-to-member-function to a derived class
/// pointer-to-member-function
///
///
/// The `cir.derived_method` operation casts a pointer-to-member-function of
/// type `Ret (Base::*)(Args)` to a pointer-to-member-function of type
/// `Ret (Derived::*)(Args)`, where `Base` is a non-virtual base class of
/// `Derived`.
///
/// The `offset` parameter gives the offset in bytes of the `Base` base class
/// subobject within a `Derived` object.
///
/// Example:
///
/// ```
/// %1 = cir.derived_method %0 [16] : !cir.method<!cir.func<(!s32i)> in !rec_Base> -> !cir.method<!cir.func<(!s32i)> in !rec_Derived>
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct DerivedMethod {
    pub result: super::ValueId,
    pub result_ty: crate::types::Type,
    /// CIR type that represents C++ pointer-to-member-function type
    pub src: super::ValueId,
    /// index attribute
    pub offset: crate::attrs::Attribute,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.extract_member`
/// Extract the value of a member of a record value
///
/// The `cir.extract_member` operation extracts the value of a particular member
/// from the input record. Unlike `cir.get_member` which derives pointers, this
/// operation operates on values. It takes a value of record type and extracts
/// the value of the specified record member from the input record value.
///
/// Currently `cir.extract_member` does not work on unions.
///
/// Example:
///
/// ```
/// // Suppose we have a record with multiple members.
/// !s32i = !cir.int<s, 32>
/// !s8i = !cir.int<s, 32>
/// !record_ty = !cir.record<"struct.Bar" {!s32i, !s8i}>
///
/// // And suppose we have a value of the record type.
/// %0 = cir.const #cir.const_record<{#cir.int<1> : !s32i,
///                               #cir.int<2> : !s8i}> : !record_ty
///
/// // Extract the value of the second member of the record.
/// %1 = cir.extract_member %0[1] : !record_ty -> !s8i
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct ExtractMember {
    pub result: super::ValueId,
    pub result_ty: crate::types::Type,
    /// CIR record type
    pub record: super::ValueId,
    /// 64-bit signless integer attribute
    pub index: crate::attrs::Attribute,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.get_bitfield`
/// Get the information for a bitfield member
///
/// The `cir.get_bitfield` operation provides a load-like access to
/// a bit field of a record.
///
/// It expects a name if a bit field, a pointer to a storage in the
/// base record, a type of the storage, a name of the bitfield,
/// a size the bit field, an offset of the bit field and a sign.
///
/// A unit attribute `volatile` can be used to indicate a volatile load of the
/// bitfield.
/// ```
///   cir.get_bitfield(#bfi, %0 {is_volatile} : !cir.ptr<!u64i>) -> !s32i
/// ```
///
/// Example:
/// Suppose we have a struct with multiple bitfields stored in
/// different members. The `cir.get_bitfield` operation gets the value
/// of the bitfield.
/// ```C++
/// typedef struct {
///   int a : 4;
///   int b : 27;
///   int c : 17;
///   int d : 2;
///   int e : 15;
/// } S;
///
/// int load_bitfield(S& s) {
///   return s.e;
/// }
/// ```
///
/// ```
/// // 'e' is in the storage with the index 1
/// !cir.struct<"S" packed {!u64i, !u16i,
///                         pad !cir.array<!u8i x 2>}>
/// #bfi_e = #cir.bitfield_info<name = "e", storage_type = !u16i, size = 15,
///                             offset = 0, is_signed = true>
///
/// %2 = cir.load %0 : !cir.ptr<!cir.ptr<!record_type>>, !cir.ptr<!record_type>
/// %3 = cir.get_member %2[1] {name = "e"} : !cir.ptr<!record_type>
///                                                          -> !cir.ptr<!u16i>
/// %4 = cir.get_bitfield align(4) (#bfi_e, %3 : !cir.ptr<!u16i>) -> !s32i
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetBitfield {
    pub result: super::ValueId,
    pub result_ty: crate::types::Type,
    /// the address to load from
    pub addr: super::ValueId,
    /// Represents info for a bit-field member
    pub bitfield_info: crate::attrs::Attribute,
    /// 64-bit signless integer attribute
    pub alignment: crate::attrs::Attribute,
    /// unit attribute
    pub is_volatile: bool,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.get_element`
/// Get the address of an array element
///
/// The `cir.get_element` operation gets the address of a particular element
/// from the `base` array.
///
/// It expects a pointer to the `base` array and the `index` of the element.
/// The result pointer preserves the address space of the base pointer.
///
/// Example:
/// ```
/// // Suppose we have a array.
/// !s32i = !cir.int<s, 32>
/// !arr_ty = !cir.array<!s32i x 4>
///
/// // Get the address of the element at index 1.
/// %elem_1 = cir.get_element %0[1 : !s32i] : !cir.ptr<!array_ty> -> !cir.ptr<!s32i>
///
/// // Get the address of the element at index %i.
/// %i = ...
/// %elem_i = cir.get_element %0[%i : !s32i] : !cir.ptr<!array_ty> -> !cir.ptr<!s32i>
///
/// // With address space (e.g., GPU private memory):
/// %elem_gpu = cir.get_element %gpu_arr[%i : !s32i] :
///   !cir.ptr<!cir.array<!s32i x 10>, target_address_space(5)> ->
///   !cir.ptr<!s32i, target_address_space(5)>
///
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetElement {
    pub result: super::ValueId,
    pub result_ty: crate::types::Type,
    /// the base address of the array
    pub base: super::ValueId,
    /// the index of the element
    pub index: super::ValueId,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.get_member`
/// Get the address of a member of a record
///
/// The `cir.get_member` operation gets the address of a particular named
/// member from the input record.
///
/// It expects a pointer to the base record as well as the name of the member
/// and its field index.
///
/// Example:
/// ```
/// // Suppose we have a record with multiple members.
/// !s32i = !cir.int<s, 32>
/// !s8i = !cir.int<s, 8>
/// !ty_B = !cir.record<"struct.B" {!s32i, !s8i}>
///
/// // Get the address of the member at index 1.
/// %1 = cir.get_member %0[1] {name = "i"} : (!cir.ptr<!ty_B>) -> !cir.ptr<!s8i>
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetMember {
    pub result: super::ValueId,
    pub result_ty: crate::types::Type,
    /// CIR pointer type
    pub addr: super::ValueId,
    /// string attribute
    pub name: String,
    /// index attribute
    pub index_attr: crate::attrs::Attribute,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.get_method`
/// Resolve a method to a function pointer as callee
///
/// The `cir.get_method` operation takes a pointer to method (!cir.method) and
/// a pointer to a class object (!cir.ptr<!cir.record>>) as input, and
/// yields a function pointer that points to the actual function corresponding
/// to the input method. The operation also applies any necessary adjustments to
/// the input object pointer for calling the method and yields the adjusted
/// pointer.
///
/// This operation is generated when calling a method through a pointer-to-
/// member-function in C++:
///
/// ```cpp
/// // Foo *object;
/// // int arg;
/// // void (Foo::*method)(int);
///
/// (object->*method)(arg);
/// ```
///
/// The code above will generate CIR similar to:
///
/// ```
/// %callee, %this = cir.get_method %method, %object
/// cir.call %callee(%this, %arg)
/// ```
///
/// The method type must match the callee type. That is:
/// - The return type of the method must match the return type of the callee.
/// - The first parameter of the callee must have type `!cir.ptr<!cir.void>`.
/// - Types of other parameters of the callee must match the method's
///   parameters after the implicit `this` pointer.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetMethod {
    pub callee: super::ValueId,
    pub callee_ty: crate::types::Type,
    pub adjusted_this: super::ValueId,
    pub adjusted_this_ty: crate::types::Type,
    /// CIR type that represents C++ pointer-to-member-function type
    pub method: super::ValueId,
    /// pointer to record type
    pub object: super::ValueId,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.get_runtime_member`
/// Get the address of a member of a record
///
/// The `cir.get_runtime_member` operation gets the address of a member from
/// the input record. The target member is given by a value of type
/// `!cir.data_member` (i.e. a pointer-to-data-member value).
///
/// This operation differs from `cir.get_member` in when the target member can
/// be determined. For the `cir.get_member` operation, the target member is
/// specified as a constant index so the member it returns access to is known
/// when the operation is constructed. For the `cir.get_runtime_member`
/// operation, the target member is given through a pointer-to-data-member
/// value which is unknown until the program being compiled is executed. In
/// other words, `cir.get_member` represents a normal member access through the
/// `.` operator in C/C++:
///
/// ```cpp
/// struct Foo { int x; };
/// Foo f;
/// (void)f.x;  // cir.get_member
/// ```
///
/// And `cir.get_runtime_member` represents a member access through the `.*` or
/// the `->*` operator in C++:
///
/// ```cpp
/// struct Foo { int x; }
/// Foo f;
/// Foo *p;
/// int Foo::*member;
///
/// (void)f.*member;   // cir.get_runtime_member
/// (void)p->*member;  // cir.get_runtime_member
/// ```
///
/// This operation expects a pointer to the base record as well as the pointer
/// to the target member.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct GetRuntimeMember {
    pub result: super::ValueId,
    pub result_ty: crate::types::Type,
    /// pointer to record type
    pub addr: super::ValueId,
    /// CIR type that represents a pointer-to-data-member in C++
    pub member: super::ValueId,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.insert_member`
/// Overwrite the value of a member of a record value
///
/// The `cir.insert_member` operation overwrites the value of a particular
/// member in the input record, and returns the modified record. The result of
/// this operation is equal to the input record, except for the member specified
/// by `index_attr` whose value is equal to the given value.
///
/// This operation is named after the LLVM instruction `insertvalue`.
///
/// Currently `cir.insert_member` does not work on unions.
///
/// Example:
///
/// ```
/// // Suppose we have a record with multiple members.
/// !s32i = !cir.int<s, 32>
/// !s8i = !cir.int<s, 32>
/// !record_ty = !cir.record<"struct.Bar" {!s32i, !s8i}>
///
/// // And suppose we have a value of the record type.
/// %0 = cir.const #cir.const_record<{#cir.int<1> : !s32i, #cir.int<2> : !s8i}> : !record_ty
/// // %0 is {1, 2}
///
/// // Overwrite the second member of the record value.
/// %1 = cir.const #cir.int<3> : !s8i
/// %2 = cir.insert_member %0[1], %1 : !record_ty, !s8i
/// // %2 is {1, 3}
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct InsertMember {
    pub result: super::ValueId,
    pub result_ty: crate::types::Type,
    /// CIR record type
    pub record: super::ValueId,
    /// 64-bit signless integer attribute
    pub index: crate::attrs::Attribute,
    /// CIR void type or CIR bool type or CIR array type or CIR vector type or Integer type with arbitrary precision up to a fixed limit or single float type or double float type or f16 type or bf16 type or f80 type or f128 type or long double type or CIR pointer type or CIR function type or CIR struct/class type or CIR union type or CIR complex type or CIR type that is used for the vptr member of C++ objects or CIR type that represents a pointer-to-data-member in C++ or CIR type that represents C++ pointer-to-member-function type or CIR exception handling token type or CIR cleanup token type or CIR catch token type
    pub value: super::ValueId,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.lifetime.end`
/// Marks the end of the lifetime of a variable produced by a cir.alloca operation
///
/// The `cir.lifetime.end` operation marks the end of the lifetime of the
/// storage pointed to by `$ptr`. After this operation the underlying storage
/// is considered dead, and the optimizer is free to reuse the storage for
/// other purposes, until a subsequent `cir.lifetime.start` on the same
/// pointer revives it.
///
/// The `cir.scope` is the operation that models the block scope of the C/C++
/// source. Once ClangIR is no longer structured, `cir.scope` can no longer express
/// the lifetime of a local variable. This happens, for example, after `FlattenCFG`,
/// where `cir.scope` regions are dissolved into plain basic blocks, or after
/// `HoistAllocas`, where an alloca is moved to the function entry so that its
/// position no longer reflects the scope it was declared in. In that form, these
/// lifetime markers are what delimit the beginning and end of a variable's
/// lifetime.
///
/// The verifier requires `$ptr` to be produced by a `cir.alloca`.
/// `cir.lifetime.end` should be preceded by a matching `cir.lifetime.start` on
/// the same pointer on every control-flow path that reaches it.
///
/// This operation corresponds to the LLVM intrinsic `llvm.lifetime.end`.
///
/// Example:
/// ```
/// cir.lifetime.end %ptr : !cir.ptr<!s32i>
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct LifetimeEnd {
    /// CIR pointer type
    pub ptr: super::ValueId,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.lifetime.start`
/// Marks the start of the lifetime of a variable produced by a cir.alloca operation
///
/// The `cir.lifetime.start` operation marks the beginning of the lifetime
/// of the storage pointed to by `$ptr`. Between this operation and a
/// matching `cir.lifetime.end` on the same pointer, the underlying storage
/// is considered live; outside that range it is considered dead, and the
/// optimizer is free to reuse the storage for other purposes.
///
/// The `cir.scope` is the operation that models the block scope of the C/C++
/// source. Once ClangIR is no longer structured, `cir.scope` can no longer express
/// the lifetime of a local variable. This happens, for example, after `FlattenCFG`,
/// where `cir.scope` regions are dissolved into plain basic blocks, or after
/// `HoistAllocas`, where an alloca is moved to the function entry so that its
/// position no longer reflects the scope it was declared in. In that form, these
/// lifetime markers are what delimit the beginning and end of a variable's
/// lifetime.
///
/// The verifier requires `$ptr` to be produced by a `cir.alloca`. For the
/// lifetime to be meaningful, a matching `cir.lifetime.end` on the same
/// pointer should follow on every control-flow path. This is different from
/// LLVM, where an `llvm.lifetime.start` may appear without a matching
/// `llvm.lifetime.end` -- there the storage is also implicitly marked dead
/// when the function returns (see the
/// [LLVM LangRef](https://llvm.org/docs/LangRef.html#int-lifestart)).
///
/// This operation corresponds to the LLVM intrinsic `llvm.lifetime.start`.
///
/// Example:
/// ```
/// cir.lifetime.start %ptr : !cir.ptr<!s32i>
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct LifetimeStart {
    /// CIR pointer type
    pub ptr: super::ValueId,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.load`
/// Load value from memory adddress
///
/// `cir.load` reads a value (lvalue to rvalue conversion) given an address
/// backed up by a `cir.ptr` type. A unit attribute `deref` can be used to
/// mark the resulting value as used by another operation to dereference
/// a pointer. A unit attribute `volatile` can be used to indicate a volatile
/// loading. Load can be marked atomic by using `atomic(<mem_order>)`.
///
/// `alignment` can be used to specify an alignment that's different from the
/// default, which is computed from `result`'s type ABI data layout.
///
/// A unit attribute `invariant` can be used to indicate that the loaded memory
/// never changes, mapping to LLVM IR's `!invariant.load` metadata.
///
/// Example:
///
/// ```
///
/// // Read from local variable, address in %0.
/// %1 = cir.load %0 : !cir.ptr<i32>, i32
///
/// // Load address from memory at address %0. %3 is used by at least one
/// // operation that dereferences a pointer.
/// %3 = cir.load deref %0 : !cir.ptr<!cir.ptr<i32>>
///
/// // Perform a volatile load from address in %0.
/// %4 = cir.load volatile %0 : !cir.ptr<i32>, i32
///
/// // Perform an invariant load from address in %0.
/// %5 = cir.load invariant %0 : !cir.ptr<i32>, i32
///
/// // Others
/// %x = cir.load align(16) atomic(seq_cst) %0 : !cir.ptr<i32>, i32
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Load {
    pub result: super::ValueId,
    pub result_ty: crate::types::Type,
    /// the address to load from
    pub addr: super::ValueId,
    /// unit attribute
    pub is_deref: bool,
    /// unit attribute
    pub is_volatile: bool,
    /// unit attribute
    pub is_nontemporal: bool,
    /// 64-bit signless integer attribute
    pub alignment: Option<crate::attrs::Attribute>,
    /// sync scope kind
    pub sync_scope: Option<crate::enums::SyncScopeKind>,
    /// Memory order according to C++11 memory model
    pub mem_order: Option<crate::enums::MemOrder>,
    /// unit attribute
    pub invariant: bool,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.ptr_diff`
/// Pointer subtraction arithmetic
///
/// The cir.ptr_diff operation computes the difference between two pointers that
/// have the same element type.
///
/// The result reflects the ABI-defined size of the pointed-to type. For example,
/// subtracting two !cir.ptr<!u64i> values may yield 1, representing an 8-byte
/// difference. In contrast, for pointers to void or function types, a result of
/// 8 corresponds to an 8-byte difference.
///
/// For pointers to types whose size are not aligned with the target data
/// layout, the size is generally rounded to the next power of 2 bits. For
/// example, subtracting two !cir.ptr<!s24i> values for the _BitInt(24) type may
/// yield 1, representing a 4-byte difference (as opposed to a 3-byte
/// difference).
///
/// Example:
///
/// ```
/// %7 = cir.ptr_diff %0, %1 : !cir.ptr<!u64i> -> !u64i
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PtrDiff {
    pub result: super::ValueId,
    pub result_ty: crate::types::Type,
    /// CIR pointer type
    pub lhs: super::ValueId,
    /// CIR pointer type
    pub rhs: super::ValueId,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.ptr_stride`
/// Pointer access with stride
///
/// The `cir.ptr_stride` operation computes a new pointer from a base pointer
/// and an integer stride, similar to a single-index `getelementptr` in LLVM IR.
/// It moves the pointer by `stride * sizeof(element_type)` bytes.
///
/// ```
/// %3 = cir.const 0 : i32
/// %3 = cir.ptr_stride %1, %2 : (!cir.ptr<i32>, i32) -> !cir.ptr<i32>
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct PtrStride {
    pub result: super::ValueId,
    pub result_ty: crate::types::Type,
    /// CIR pointer type
    pub base: super::ValueId,
    /// fundamental integer type
    pub stride: super::ValueId,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.set_bitfield`
/// Set the value of a bitfield member
///
/// The `cir.set_bitfield` operation provides a store-like access to
/// a bit field of a record.
///
/// A bitfield info attribute must be provided to describe the location of
/// the bitfield within the memory referenced by the $addr argument.
/// The $src argument is inserted at the appropriate place in the memory and
/// the value that was stored. Returns the value being stored.
///
/// A unit attribute `volatile` can be used to indicate a volatile store of the
/// bitfield.
///   ```
///     cir.set_bitfield(#bfi, %0 : !cir.ptr<!u32i>, %1 : !s32i) {is_volatile}
///                                                                    -> !s32i
///   ```
///
/// Example.
/// Suppose we have a struct with multiple bitfields stored in
/// different storages. The `cir.set_bitfield` operation sets the value
/// of the bitfield.
/// ```C++
/// typedef struct {
///   int a : 4;
///   int b : 27;
///   int c : 17;
///   int d : 2;
///   int e : 15;
/// } S;
///
/// void store_bitfield(S& s) {
///   s.e = 3;
/// }
/// ```
///
/// ```
/// // 'e' is in the storage with the index 1
/// !record_type = !cir.struct<"S" packed {!u64i, !u16i,
///                                        pad !cir.array<!u8i x 2>}>
/// #bfi_e = #cir.bitfield_info<name = "e", storage_type = !u16i, size = 15,
///                             offset = 0, is_signed = true>
///
/// %1 = cir.const #cir.int<3> : !s32i
/// %2 = cir.load %0 : !cir.ptr<!cir.ptr<!record_type>>, !cir.ptr<!record_type>
/// %3 = cir.get_member %2[1] {name = "e"} : !cir.ptr<!record_type>
///                                                          -> !cir.ptr<!u16i>
/// %4 = cir.set_bitfield align(4) (#bfi_e, %3 : !cir.ptr<!u16i>, %1 : !s32i)
///                                                                    -> !s32i
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct SetBitfield {
    pub result: super::ValueId,
    pub result_ty: crate::types::Type,
    /// the address to store the value
    pub addr: super::ValueId,
    /// CIR void type or CIR bool type or CIR array type or CIR vector type or Integer type with arbitrary precision up to a fixed limit or single float type or double float type or f16 type or bf16 type or f80 type or f128 type or long double type or CIR pointer type or CIR function type or CIR struct/class type or CIR union type or CIR complex type or CIR type that is used for the vptr member of C++ objects or CIR type that represents a pointer-to-data-member in C++ or CIR type that represents C++ pointer-to-member-function type or CIR exception handling token type or CIR cleanup token type or CIR catch token type
    pub src: super::ValueId,
    /// Represents info for a bit-field member
    pub bitfield_info: crate::attrs::Attribute,
    /// 64-bit signless integer attribute
    pub alignment: crate::attrs::Attribute,
    /// unit attribute
    pub is_volatile: bool,
    pub loc: Option<crate::ast::SourceLocation>,
}
/// `cir.store`
/// Store value to memory address
///
/// `cir.store` stores a value (first operand) to the memory address specified
/// in the second operand. A unit attribute `volatile` can be used to indicate
/// a volatile store. Store's can be marked atomic by using
/// `atomic(<mem_order>)`.
///
/// `alignment` can be used to specify an alignment that's different from the
/// default, which is computed from `result`'s type ABI data layout.
///
/// Example:
///
/// ```
/// // Store a function argument to local storage, address in %0.
/// cir.store %arg0, %0 : i32, !cir.ptr<i32>
///
/// // Perform a volatile store into memory location at the address in %0.
/// cir.store volatile %arg0, %0 : i32, !cir.ptr<i32>
///
/// // Others
/// cir.store align(16) atomic(seq_cst) %x, %addr : i32, !cir.ptr<i32>
/// ```
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
pub struct Store {
    /// CIR void type or CIR bool type or CIR array type or CIR vector type or Integer type with arbitrary precision up to a fixed limit or single float type or double float type or f16 type or bf16 type or f80 type or f128 type or long double type or CIR pointer type or CIR function type or CIR struct/class type or CIR union type or CIR complex type or CIR type that is used for the vptr member of C++ objects or CIR type that represents a pointer-to-data-member in C++ or CIR type that represents C++ pointer-to-member-function type or CIR exception handling token type or CIR cleanup token type or CIR catch token type
    pub value: super::ValueId,
    /// the address to store the value
    pub addr: super::ValueId,
    /// unit attribute
    pub is_volatile: bool,
    /// unit attribute
    pub is_nontemporal: bool,
    /// 64-bit signless integer attribute
    pub alignment: Option<crate::attrs::Attribute>,
    /// sync scope kind
    pub sync_scope: Option<crate::enums::SyncScopeKind>,
    /// Memory order according to C++11 memory model
    pub mem_order: Option<crate::enums::MemOrder>,
    pub loc: Option<crate::ast::SourceLocation>,
}